//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Workflow
{
	public partial interface IStatus {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class BaseStatus: QueenbeeSDK.Interface.Workflow.IStatus {}
	public partial class TaskStatus: QueenbeeSDK.Interface.Workflow.IStatus {}
	public partial class WorkflowStatus: QueenbeeSDK.Interface.Workflow.IStatus {}
}
