//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Base
{
	public partial interface IMetadata {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class License: QueenbeeSDK.Interface.Base.IMetadata {}
	public partial class Maintainer: QueenbeeSDK.Interface.Base.IMetadata {}
	public partial class MetaData: QueenbeeSDK.Interface.Base.IMetadata {}
}
