//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Job
{
	public partial interface IJob {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class Job: QueenbeeSDK.Interface.Job.IJob {}
}
