//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Job
{
	public partial interface IRun {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class RunStatus: QueenbeeSDK.Interface.Job.IRun {}
	public partial class StepStatus: QueenbeeSDK.Interface.Job.IRun {}
}
