//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Job
{
	public partial interface IStatus {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class BaseStatus: QueenbeeSDK.Interface.Job.IStatus {}
	public partial class JobStatus: QueenbeeSDK.Interface.Job.IStatus {}
	public partial class StepStatus: QueenbeeSDK.Interface.Job.IStatus {}
}
