//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Inputs
{
	public partial interface IDag {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class DAGArrayInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
	public partial class DAGBooleanInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
	public partial class DAGFileInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
	public partial class DAGFolderInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
	public partial class DAGGenericInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
	public partial class DAGIntegerInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
	public partial class DAGJSONObjectInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
	public partial class DAGNumberInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
	public partial class DAGPathInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
	public partial class DAGStringInput: QueenbeeSDK.Interface.Io.Inputs.IDag {}
}
