//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Inputs
{
	public partial interface IFunction {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class FunctionArrayInput: QueenbeeSDK.Interface.Io.Inputs.IFunction {}
	public partial class FunctionBooleanInput: QueenbeeSDK.Interface.Io.Inputs.IFunction {}
	public partial class FunctionFileInput: QueenbeeSDK.Interface.Io.Inputs.IFunction {}
	public partial class FunctionFolderInput: QueenbeeSDK.Interface.Io.Inputs.IFunction {}
	public partial class FunctionIntegerInput: QueenbeeSDK.Interface.Io.Inputs.IFunction {}
	public partial class FunctionJSONObjectInput: QueenbeeSDK.Interface.Io.Inputs.IFunction {}
	public partial class FunctionNumberInput: QueenbeeSDK.Interface.Io.Inputs.IFunction {}
	public partial class FunctionPathInput: QueenbeeSDK.Interface.Io.Inputs.IFunction {}
	public partial class FunctionStringInput: QueenbeeSDK.Interface.Io.Inputs.IFunction {}
}
