//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Inputs
{
	public partial interface IJob {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class JobArgument: QueenbeeSDK.Interface.Io.Inputs.IJob {}
	public partial class JobPathArgument: QueenbeeSDK.Interface.Io.Inputs.IJob {}
}
