//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Inputs
{
	public partial interface IStep {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class StepArrayInput: QueenbeeSDK.Interface.Io.Inputs.IStep {}
	public partial class StepBooleanInput: QueenbeeSDK.Interface.Io.Inputs.IStep {}
	public partial class StepFileInput: QueenbeeSDK.Interface.Io.Inputs.IStep {}
	public partial class StepFolderInput: QueenbeeSDK.Interface.Io.Inputs.IStep {}
	public partial class StepIntegerInput: QueenbeeSDK.Interface.Io.Inputs.IStep {}
	public partial class StepJSONObjectInput: QueenbeeSDK.Interface.Io.Inputs.IStep {}
	public partial class StepNumberInput: QueenbeeSDK.Interface.Io.Inputs.IStep {}
	public partial class StepPathInput: QueenbeeSDK.Interface.Io.Inputs.IStep {}
	public partial class StepStringInput: QueenbeeSDK.Interface.Io.Inputs.IStep {}
}
