//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Inputs
{
	public partial interface ITask {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class TaskArgument: QueenbeeSDK.Interface.Io.Inputs.ITask {}
	public partial class TaskPathArgument: QueenbeeSDK.Interface.Io.Inputs.ITask {}
}
