//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Inputs
{
	public partial interface IWorkflow {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class WorkflowArgument: QueenbeeSDK.Interface.Io.Inputs.IWorkflow {}
	public partial class WorkflowPathArgument: QueenbeeSDK.Interface.Io.Inputs.IWorkflow {}
}
