//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Outputs
{
	public partial interface IDag {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class DAGArrayOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
	public partial class DAGBooleanOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
	public partial class DAGFileOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
	public partial class DAGFolderOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
	public partial class DAGGenericOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
	public partial class DAGIntegerOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
	public partial class DAGJSONObjectOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
	public partial class DAGNumberOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
	public partial class DAGPathOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
	public partial class DAGStringOutput: QueenbeeSDK.Interface.Io.Outputs.IDag {}
}
