//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Outputs
{
	public partial interface IFunction {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class FunctionArrayOutput: QueenbeeSDK.Interface.Io.Outputs.IFunction {}
	public partial class FunctionBooleanOutput: QueenbeeSDK.Interface.Io.Outputs.IFunction {}
	public partial class FunctionFileOutput: QueenbeeSDK.Interface.Io.Outputs.IFunction {}
	public partial class FunctionFolderOutput: QueenbeeSDK.Interface.Io.Outputs.IFunction {}
	public partial class FunctionIntegerOutput: QueenbeeSDK.Interface.Io.Outputs.IFunction {}
	public partial class FunctionJSONObjectOutput: QueenbeeSDK.Interface.Io.Outputs.IFunction {}
	public partial class FunctionNumberOutput: QueenbeeSDK.Interface.Io.Outputs.IFunction {}
	public partial class FunctionPathOutput: QueenbeeSDK.Interface.Io.Outputs.IFunction {}
	public partial class FunctionStringOutput: QueenbeeSDK.Interface.Io.Outputs.IFunction {}
}
