//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Outputs
{
	public partial interface IStep {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class StepArrayOutput: QueenbeeSDK.Interface.Io.Outputs.IStep {}
	public partial class StepBooleanOutput: QueenbeeSDK.Interface.Io.Outputs.IStep {}
	public partial class StepFileOutput: QueenbeeSDK.Interface.Io.Outputs.IStep {}
	public partial class StepFolderOutput: QueenbeeSDK.Interface.Io.Outputs.IStep {}
	public partial class StepIntegerOutput: QueenbeeSDK.Interface.Io.Outputs.IStep {}
	public partial class StepJSONObjectOutput: QueenbeeSDK.Interface.Io.Outputs.IStep {}
	public partial class StepNumberOutput: QueenbeeSDK.Interface.Io.Outputs.IStep {}
	public partial class StepPathOutput: QueenbeeSDK.Interface.Io.Outputs.IStep {}
	public partial class StepStringOutput: QueenbeeSDK.Interface.Io.Outputs.IStep {}
}
