//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io.Outputs
{
	public partial interface ITask {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class TaskPathReturn: QueenbeeSDK.Interface.Io.Outputs.ITask {}
	public partial class TaskReturn: QueenbeeSDK.Interface.Io.Outputs.ITask {}
}
