//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Repository
{
	public partial interface IIndex {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class RepositoryIndex: QueenbeeSDK.Interface.Repository.IIndex {}
	public partial class RepositoryMetadata: QueenbeeSDK.Interface.Repository.IIndex {}
}
