//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Repository
{
	public partial interface IPackage {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class PackageVersion: QueenbeeSDK.Interface.Repository.IPackage {}
}
