/* 
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace QueenbeeSDK.Model
{
    /// <summary>
    /// Type enum for items in a list.
    /// </summary>
    /// <value>Type enum for items in a list.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ItemType
    {
        /// <summary>
        /// Enum String for value: String
        /// </summary>
        [EnumMember(Value = "String")]
        String = 1,

        /// <summary>
        /// Enum Integer for value: Integer
        /// </summary>
        [EnumMember(Value = "Integer")]
        Integer = 2,

        /// <summary>
        /// Enum Number for value: Number
        /// </summary>
        [EnumMember(Value = "Number")]
        Number = 3,

        /// <summary>
        /// Enum Boolean for value: Boolean
        /// </summary>
        [EnumMember(Value = "Boolean")]
        Boolean = 4,

        /// <summary>
        /// Enum Folder for value: Folder
        /// </summary>
        [EnumMember(Value = "Folder")]
        Folder = 5,

        /// <summary>
        /// Enum Array for value: Array
        /// </summary>
        [EnumMember(Value = "Array")]
        Array = 6,

        /// <summary>
        /// Enum Object for value: Object
        /// </summary>
        [EnumMember(Value = "Object")]
        Object = 7

    }

}
