/* 
 * Queenbee Queenbee Schema
 *
 * Documentation for Queenbee queenbee schema.
 *
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace QueenbeeSDK
{
    /// <summary>
    /// Type enum for items in a list.
    /// </summary>
    /// <value>Type enum for items in a list.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ItemType
    {
        /// <summary>
        /// Enum Generic for value: Generic
        /// </summary>
        [EnumMember(Value = "Generic")]
        Generic = 1,

        /// <summary>
        /// Enum String for value: String
        /// </summary>
        [EnumMember(Value = "String")]
        String = 2,

        /// <summary>
        /// Enum Integer for value: Integer
        /// </summary>
        [EnumMember(Value = "Integer")]
        Integer = 3,

        /// <summary>
        /// Enum Number for value: Number
        /// </summary>
        [EnumMember(Value = "Number")]
        Number = 4,

        /// <summary>
        /// Enum Boolean for value: Boolean
        /// </summary>
        [EnumMember(Value = "Boolean")]
        Boolean = 5,

        /// <summary>
        /// Enum Folder for value: Folder
        /// </summary>
        [EnumMember(Value = "Folder")]
        Folder = 6,

        /// <summary>
        /// Enum Array for value: Array
        /// </summary>
        [EnumMember(Value = "Array")]
        Array = 7,

        /// <summary>
        /// Enum JSONObject for value: JSONObject
        /// </summary>
        [EnumMember(Value = "JSONObject")]
        JSONObject = 8

    }

}
