//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Operator
{
	public partial interface IOperator {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class DockerConfig: QueenbeeSDK.Interface.Operator.IOperator {}
	public partial class LocalConfig: QueenbeeSDK.Interface.Operator.IOperator {}
	public partial class Operator: QueenbeeSDK.Interface.Operator.IOperator {}
	public partial class OperatorConfig: QueenbeeSDK.Interface.Operator.IOperator {}
}
