/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing ArtifactSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArtifactSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArtifactSource
        //private ArtifactSource instance;

        public ArtifactSourceTests()
        {
            // TODO uncomment below to create an instance of ArtifactSource
            //instance = new ArtifactSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArtifactSource
        /// </summary>
        [Fact]
        public void ArtifactSourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ArtifactSource
            //Assert.IsInstanceOfType<ArtifactSource> (instance, "variable 'instance' is a ArtifactSource");
        }

        /// <summary>
        /// Test deserialize a ProjectFolder from type ArtifactSource
        /// </summary>
        [Fact]
        public void ProjectFolderDeserializeFromArtifactSourceTest()
        {
            // TODO uncomment below to test deserialize a ProjectFolder from type ArtifactSource
            //Assert.IsInstanceOf<ArtifactSource>(JsonConvert.DeserializeObject<ArtifactSource>(new ProjectFolder().ToJson()));
        }
        /// <summary>
        /// Test deserialize a S3 from type ArtifactSource
        /// </summary>
        [Fact]
        public void S3DeserializeFromArtifactSourceTest()
        {
            // TODO uncomment below to test deserialize a S3 from type ArtifactSource
            //Assert.IsInstanceOf<ArtifactSource>(JsonConvert.DeserializeObject<ArtifactSource>(new S3().ToJson()));
        }
        /// <summary>
        /// Test deserialize a HTTP from type ArtifactSource
        /// </summary>
        [Fact]
        public void HTTPDeserializeFromArtifactSourceTest()
        {
            // TODO uncomment below to test deserialize a HTTP from type ArtifactSource
            //Assert.IsInstanceOf<ArtifactSource>(JsonConvert.DeserializeObject<ArtifactSource>(new HTTP().ToJson()));
        }

        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Fact]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
