/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing DAGArrayInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DAGArrayInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DAGArrayInput
        //private DAGArrayInput instance;

        public DAGArrayInputTests()
        {
            // TODO uncomment below to create an instance of DAGArrayInput
            //instance = new DAGArrayInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DAGArrayInput
        /// </summary>
        [Fact]
        public void DAGArrayInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DAGArrayInput
            //Assert.IsInstanceOfType<DAGArrayInput> (instance, "variable 'instance' is a DAGArrayInput");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Fact]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Default'
        /// </summary>
        [Fact]
        public void DefaultTest()
        {
            // TODO unit test for the property 'Default'
        }
        /// <summary>
        /// Test the property 'Spec'
        /// </summary>
        [Fact]
        public void SpecTest()
        {
            // TODO unit test for the property 'Spec'
        }
        /// <summary>
        /// Test the property 'ItemsType'
        /// </summary>
        [Fact]
        public void ItemsTypeTest()
        {
            // TODO unit test for the property 'ItemsType'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
