/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing DAGBooleanOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DAGBooleanOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DAGBooleanOutput
        //private DAGBooleanOutput instance;

        public DAGBooleanOutputTests()
        {
            // TODO uncomment below to create an instance of DAGBooleanOutput
            //instance = new DAGBooleanOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DAGBooleanOutput
        /// </summary>
        [Fact]
        public void DAGBooleanOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DAGBooleanOutput
            //Assert.IsInstanceOfType<DAGBooleanOutput> (instance, "variable 'instance' is a DAGBooleanOutput");
        }


        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
