/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing DAGObjectInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DAGObjectInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DAGObjectInput
        //private DAGObjectInput instance;

        public DAGObjectInputTests()
        {
            // TODO uncomment below to create an instance of DAGObjectInput
            //instance = new DAGObjectInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DAGObjectInput
        /// </summary>
        [Fact]
        public void DAGObjectInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DAGObjectInput
            //Assert.IsInstanceOfType<DAGObjectInput> (instance, "variable 'instance' is a DAGObjectInput");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Fact]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Default'
        /// </summary>
        [Fact]
        public void DefaultTest()
        {
            // TODO unit test for the property 'Default'
        }
        /// <summary>
        /// Test the property 'Spec'
        /// </summary>
        [Fact]
        public void SpecTest()
        {
            // TODO unit test for the property 'Spec'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
