/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing DAGPathOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DAGPathOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DAGPathOutput
        //private DAGPathOutput instance;

        public DAGPathOutputTests()
        {
            // TODO uncomment below to create an instance of DAGPathOutput
            //instance = new DAGPathOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DAGPathOutput
        /// </summary>
        [Fact]
        public void DAGPathOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DAGPathOutput
            //Assert.IsInstanceOfType<DAGPathOutput> (instance, "variable 'instance' is a DAGPathOutput");
        }


        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
