/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing DAGStringInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DAGStringInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DAGStringInput
        //private DAGStringInput instance;

        public DAGStringInputTests()
        {
            // TODO uncomment below to create an instance of DAGStringInput
            //instance = new DAGStringInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DAGStringInput
        /// </summary>
        [Fact]
        public void DAGStringInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DAGStringInput
            //Assert.IsInstanceOfType<DAGStringInput> (instance, "variable 'instance' is a DAGStringInput");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
