/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing DAGStringOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DAGStringOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DAGStringOutput
        //private DAGStringOutput instance;

        public DAGStringOutputTests()
        {
            // TODO uncomment below to create an instance of DAGStringOutput
            //instance = new DAGStringOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DAGStringOutput
        /// </summary>
        [Fact]
        public void DAGStringOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DAGStringOutput
            //Assert.IsInstanceOfType<DAGStringOutput> (instance, "variable 'instance' is a DAGStringOutput");
        }

        /// <summary>
        /// Test deserialize a DAGIntegerOutput from type DAGStringOutput
        /// </summary>
        [Fact]
        public void DAGIntegerOutputDeserializeFromDAGStringOutputTest()
        {
            // TODO uncomment below to test deserialize a DAGIntegerOutput from type DAGStringOutput
            //Assert.IsInstanceOf<DAGStringOutput>(JsonConvert.DeserializeObject<DAGStringOutput>(new DAGIntegerOutput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGObjectOutput from type DAGStringOutput
        /// </summary>
        [Fact]
        public void DAGObjectOutputDeserializeFromDAGStringOutputTest()
        {
            // TODO uncomment below to test deserialize a DAGObjectOutput from type DAGStringOutput
            //Assert.IsInstanceOf<DAGStringOutput>(JsonConvert.DeserializeObject<DAGStringOutput>(new DAGObjectOutput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGBooleanOutput from type DAGStringOutput
        /// </summary>
        [Fact]
        public void DAGBooleanOutputDeserializeFromDAGStringOutputTest()
        {
            // TODO uncomment below to test deserialize a DAGBooleanOutput from type DAGStringOutput
            //Assert.IsInstanceOf<DAGStringOutput>(JsonConvert.DeserializeObject<DAGStringOutput>(new DAGBooleanOutput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGArrayOutput from type DAGStringOutput
        /// </summary>
        [Fact]
        public void DAGArrayOutputDeserializeFromDAGStringOutputTest()
        {
            // TODO uncomment below to test deserialize a DAGArrayOutput from type DAGStringOutput
            //Assert.IsInstanceOf<DAGStringOutput>(JsonConvert.DeserializeObject<DAGStringOutput>(new DAGArrayOutput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGNumberOutput from type DAGStringOutput
        /// </summary>
        [Fact]
        public void DAGNumberOutputDeserializeFromDAGStringOutputTest()
        {
            // TODO uncomment below to test deserialize a DAGNumberOutput from type DAGStringOutput
            //Assert.IsInstanceOf<DAGStringOutput>(JsonConvert.DeserializeObject<DAGStringOutput>(new DAGNumberOutput().ToJson()));
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
