/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing DAG
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DAGTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DAG
        //private DAG instance;

        public DAGTests()
        {
            // TODO uncomment below to create an instance of DAG
            //instance = new DAG();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DAG
        /// </summary>
        [Fact]
        public void DAGInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DAG
            //Assert.IsInstanceOfType<DAG> (instance, "variable 'instance' is a DAG");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Tasks'
        /// </summary>
        [Fact]
        public void TasksTest()
        {
            // TODO unit test for the property 'Tasks'
        }
        /// <summary>
        /// Test the property 'FailFast'
        /// </summary>
        [Fact]
        public void FailFastTest()
        {
            // TODO unit test for the property 'FailFast'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
