/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing DependencyType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DependencyTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DependencyType
        //private DependencyType instance;

        public DependencyTypeTests()
        {
            // TODO uncomment below to create an instance of DependencyType
            //instance = new DependencyType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DependencyType
        /// </summary>
        [Fact]
        public void DependencyTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DependencyType
            //Assert.IsInstanceOfType<DependencyType> (instance, "variable 'instance' is a DependencyType");
        }



    }

}
