/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing FromOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FromOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FromOutput
        //private FromOutput instance;

        public FromOutputTests()
        {
            // TODO uncomment below to create an instance of FromOutput
            //instance = new FromOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FromOutput
        /// </summary>
        [Fact]
        public void FromOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FromOutput
            //Assert.IsInstanceOfType<FromOutput> (instance, "variable 'instance' is a FromOutput");
        }

        /// <summary>
        /// Test deserialize a DAGFileOutput from type FromOutput
        /// </summary>
        [Fact]
        public void DAGFileOutputDeserializeFromFromOutputTest()
        {
            // TODO uncomment below to test deserialize a DAGFileOutput from type FromOutput
            //Assert.IsInstanceOf<FromOutput>(JsonConvert.DeserializeObject<FromOutput>(new DAGFileOutput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGPathOutput from type FromOutput
        /// </summary>
        [Fact]
        public void DAGPathOutputDeserializeFromFromOutputTest()
        {
            // TODO uncomment below to test deserialize a DAGPathOutput from type FromOutput
            //Assert.IsInstanceOf<FromOutput>(JsonConvert.DeserializeObject<FromOutput>(new DAGPathOutput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGFolderOutput from type FromOutput
        /// </summary>
        [Fact]
        public void DAGFolderOutputDeserializeFromFromOutputTest()
        {
            // TODO uncomment below to test deserialize a DAGFolderOutput from type FromOutput
            //Assert.IsInstanceOf<FromOutput>(JsonConvert.DeserializeObject<FromOutput>(new DAGFolderOutput().ToJson()));
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
