/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing GenericInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenericInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenericInput
        //private GenericInput instance;

        public GenericInputTests()
        {
            // TODO uncomment below to create an instance of GenericInput
            //instance = new GenericInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenericInput
        /// </summary>
        [Fact]
        public void GenericInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GenericInput
            //Assert.IsInstanceOfType<GenericInput> (instance, "variable 'instance' is a GenericInput");
        }

        /// <summary>
        /// Test deserialize a DAGStringInput from type GenericInput
        /// </summary>
        [Fact]
        public void DAGStringInputDeserializeFromGenericInputTest()
        {
            // TODO uncomment below to test deserialize a DAGStringInput from type GenericInput
            //Assert.IsInstanceOf<GenericInput>(JsonConvert.DeserializeObject<GenericInput>(new DAGStringInput().ToJson()));
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Fact]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Default'
        /// </summary>
        [Fact]
        public void DefaultTest()
        {
            // TODO unit test for the property 'Default'
        }
        /// <summary>
        /// Test the property 'Spec'
        /// </summary>
        [Fact]
        public void SpecTest()
        {
            // TODO unit test for the property 'Spec'
        }

    }

}
