/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing GenericOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenericOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenericOutput
        //private GenericOutput instance;

        public GenericOutputTests()
        {
            // TODO uncomment below to create an instance of GenericOutput
            //instance = new GenericOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenericOutput
        /// </summary>
        [Fact]
        public void GenericOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GenericOutput
            //Assert.IsInstanceOfType<GenericOutput> (instance, "variable 'instance' is a GenericOutput");
        }

        /// <summary>
        /// Test deserialize a TaskReturn from type GenericOutput
        /// </summary>
        [Fact]
        public void TaskReturnDeserializeFromGenericOutputTest()
        {
            // TODO uncomment below to test deserialize a TaskReturn from type GenericOutput
            //Assert.IsInstanceOf<GenericOutput>(JsonConvert.DeserializeObject<GenericOutput>(new TaskReturn().ToJson()));
        }
        /// <summary>
        /// Test deserialize a PathOutput from type GenericOutput
        /// </summary>
        [Fact]
        public void PathOutputDeserializeFromGenericOutputTest()
        {
            // TODO uncomment below to test deserialize a PathOutput from type GenericOutput
            //Assert.IsInstanceOf<GenericOutput>(JsonConvert.DeserializeObject<GenericOutput>(new PathOutput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a FromOutput from type GenericOutput
        /// </summary>
        [Fact]
        public void FromOutputDeserializeFromGenericOutputTest()
        {
            // TODO uncomment below to test deserialize a FromOutput from type GenericOutput
            //Assert.IsInstanceOf<GenericOutput>(JsonConvert.DeserializeObject<GenericOutput>(new FromOutput().ToJson()));
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Fact]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
