/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing InputReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InputReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InputReference
        //private InputReference instance;

        public InputReferenceTests()
        {
            // TODO uncomment below to create an instance of InputReference
            //instance = new InputReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InputReference
        /// </summary>
        [Fact]
        public void InputReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InputReference
            //Assert.IsInstanceOfType<InputReference> (instance, "variable 'instance' is a InputReference");
        }

        /// <summary>
        /// Test deserialize a InputFileReference from type InputReference
        /// </summary>
        [Fact]
        public void InputFileReferenceDeserializeFromInputReferenceTest()
        {
            // TODO uncomment below to test deserialize a InputFileReference from type InputReference
            //Assert.IsInstanceOf<InputReference>(JsonConvert.DeserializeObject<InputReference>(new InputFileReference().ToJson()));
        }
        /// <summary>
        /// Test deserialize a InputPathReference from type InputReference
        /// </summary>
        [Fact]
        public void InputPathReferenceDeserializeFromInputReferenceTest()
        {
            // TODO uncomment below to test deserialize a InputPathReference from type InputReference
            //Assert.IsInstanceOf<InputReference>(JsonConvert.DeserializeObject<InputReference>(new InputPathReference().ToJson()));
        }
        /// <summary>
        /// Test deserialize a InputFolderReference from type InputReference
        /// </summary>
        [Fact]
        public void InputFolderReferenceDeserializeFromInputReferenceTest()
        {
            // TODO uncomment below to test deserialize a InputFolderReference from type InputReference
            //Assert.IsInstanceOf<InputReference>(JsonConvert.DeserializeObject<InputReference>(new InputFolderReference().ToJson()));
        }

        /// <summary>
        /// Test the property 'Variable'
        /// </summary>
        [Fact]
        public void VariableTest()
        {
            // TODO unit test for the property 'Variable'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
