/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing IOBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IOBaseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IOBase
        //private IOBase instance;

        public IOBaseTests()
        {
            // TODO uncomment below to create an instance of IOBase
            //instance = new IOBase();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IOBase
        /// </summary>
        [Fact]
        public void IOBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IOBase
            //Assert.IsInstanceOfType<IOBase> (instance, "variable 'instance' is a IOBase");
        }

        /// <summary>
        /// Test deserialize a DAG from type IOBase
        /// </summary>
        [Fact]
        public void DAGDeserializeFromIOBaseTest()
        {
            // TODO uncomment below to test deserialize a DAG from type IOBase
            //Assert.IsInstanceOf<IOBase>(JsonConvert.DeserializeObject<IOBase>(new DAG().ToJson()));
        }

        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Fact]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Fact]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Fact]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
