/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing ItemType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemType
        //private ItemType instance;

        public ItemTypeTests()
        {
            // TODO uncomment below to create an instance of ItemType
            //instance = new ItemType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemType
        /// </summary>
        [Fact]
        public void ItemTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemType
            //Assert.IsInstanceOfType<ItemType> (instance, "variable 'instance' is a ItemType");
        }



    }

}
