/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing Maintainer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MaintainerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Maintainer
        //private Maintainer instance;

        public MaintainerTests()
        {
            // TODO uncomment below to create an instance of Maintainer
            //instance = new Maintainer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Maintainer
        /// </summary>
        [Fact]
        public void MaintainerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Maintainer
            //Assert.IsInstanceOfType<Maintainer> (instance, "variable 'instance' is a Maintainer");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Fact]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
