/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing OpenAPIGenBaseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpenAPIGenBaseModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OpenAPIGenBaseModel
        //private OpenAPIGenBaseModel instance;

        public OpenAPIGenBaseModelTests()
        {
            // TODO uncomment below to create an instance of OpenAPIGenBaseModel
            //instance = new OpenAPIGenBaseModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpenAPIGenBaseModel
        /// </summary>
        [Fact]
        public void OpenAPIGenBaseModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OpenAPIGenBaseModel
            //Assert.IsInstanceOfType<OpenAPIGenBaseModel> (instance, "variable 'instance' is a OpenAPIGenBaseModel");
        }

        /// <summary>
        /// Test deserialize a DAGFileInput from type OpenAPIGenBaseModel
        /// </summary>
        [Fact]
        public void DAGFileInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGFileInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf<OpenAPIGenBaseModel>(JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGFileInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGFolderInput from type OpenAPIGenBaseModel
        /// </summary>
        [Fact]
        public void DAGFolderInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGFolderInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf<OpenAPIGenBaseModel>(JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGFolderInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGPathInput from type OpenAPIGenBaseModel
        /// </summary>
        [Fact]
        public void DAGPathInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGPathInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf<OpenAPIGenBaseModel>(JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGPathInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGArrayInput from type OpenAPIGenBaseModel
        /// </summary>
        [Fact]
        public void DAGArrayInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGArrayInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf<OpenAPIGenBaseModel>(JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGArrayInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGObjectInput from type OpenAPIGenBaseModel
        /// </summary>
        [Fact]
        public void DAGObjectInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGObjectInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf<OpenAPIGenBaseModel>(JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGObjectInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGBooleanInput from type OpenAPIGenBaseModel
        /// </summary>
        [Fact]
        public void DAGBooleanInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGBooleanInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf<OpenAPIGenBaseModel>(JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGBooleanInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGNumberInput from type OpenAPIGenBaseModel
        /// </summary>
        [Fact]
        public void DAGNumberInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGNumberInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf<OpenAPIGenBaseModel>(JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGNumberInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGIntegerInput from type OpenAPIGenBaseModel
        /// </summary>
        [Fact]
        public void DAGIntegerInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGIntegerInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf<OpenAPIGenBaseModel>(JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGIntegerInput().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
