/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing TaskFileReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskFileReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskFileReference
        //private TaskFileReference instance;

        public TaskFileReferenceTests()
        {
            // TODO uncomment below to create an instance of TaskFileReference
            //instance = new TaskFileReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskFileReference
        /// </summary>
        [Fact]
        public void TaskFileReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskFileReference
            //Assert.IsInstanceOfType<TaskFileReference> (instance, "variable 'instance' is a TaskFileReference");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Variable'
        /// </summary>
        [Fact]
        public void VariableTest()
        {
            // TODO unit test for the property 'Variable'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
