/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing TaskPathArgument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskPathArgumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskPathArgument
        //private TaskPathArgument instance;

        public TaskPathArgumentTests()
        {
            // TODO uncomment below to create an instance of TaskPathArgument
            //instance = new TaskPathArgument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskPathArgument
        /// </summary>
        [Fact]
        public void TaskPathArgumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskPathArgument
            //Assert.IsInstanceOfType<TaskPathArgument> (instance, "variable 'instance' is a TaskPathArgument");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Fact]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'SubPath'
        /// </summary>
        [Fact]
        public void SubPathTest()
        {
            // TODO unit test for the property 'SubPath'
        }

    }

}
