/*
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing ValueFileReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValueFileReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValueFileReference
        //private ValueFileReference instance;

        public ValueFileReferenceTests()
        {
            // TODO uncomment below to create an instance of ValueFileReference
            //instance = new ValueFileReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValueFileReference
        /// </summary>
        [Fact]
        public void ValueFileReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ValueFileReference
            //Assert.IsInstanceOfType<ValueFileReference> (instance, "variable 'instance' is a ValueFileReference");
        }

        /// <summary>
        /// Test deserialize a ValueFolderReference from type ValueFileReference
        /// </summary>
        [Fact]
        public void ValueFolderReferenceDeserializeFromValueFileReferenceTest()
        {
            // TODO uncomment below to test deserialize a ValueFolderReference from type ValueFileReference
            //Assert.IsInstanceOf<ValueFileReference>(JsonConvert.DeserializeObject<ValueFileReference>(new ValueFolderReference().ToJson()));
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
