/* 
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Api;
using QueenbeeSDK.Model;
using QueenbeeSDK.Client;
using QueenbeeSDK;

using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing ValueFileReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValueFileReferenceTests
    {
        // TODO uncomment below to declare an instance variable for ValueFileReference
        //private ValueFileReference instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ValueFileReference
            //instance = new ValueFileReference();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValueFileReference
        /// </summary>
        [Test]
        public void ValueFileReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ValueFileReference
            //Assert.IsInstanceOf(typeof(ValueFileReference), instance);
        }

        /// <summary>
        /// Test deserialize a ValueFolderReference from type ValueFileReference
        /// </summary>
        [Test]
        public void ValueFolderReferenceDeserializeFromValueFileReferenceTest()
        {
            // TODO uncomment below to test deserialize a ValueFolderReference from type ValueFileReference
            //Assert.IsInstanceOf(typeof(ValueFileReference), JsonConvert.DeserializeObject<ValueFileReference>(new ValueFolderReference().ToJson()));
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
