//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Plugin
{
	public partial interface IFunction {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class Function: QueenbeeSDK.Interface.Plugin.IFunction {}
}
