//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Plugin
{
	public partial interface IPlugin {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class DockerConfig: QueenbeeSDK.Interface.Plugin.IPlugin {}
	public partial class LocalConfig: QueenbeeSDK.Interface.Plugin.IPlugin {}
	public partial class Plugin: QueenbeeSDK.Interface.Plugin.IPlugin {}
	public partial class PluginConfig: QueenbeeSDK.Interface.Plugin.IPlugin {}
}
