/* 
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Model;
using QueenbeeSDK;

using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing GenericInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenericInputTests
    {
        // TODO uncomment below to declare an instance variable for GenericInput
        //private GenericInput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GenericInput
            //instance = new GenericInput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GenericInput
        /// </summary>
        [Test]
        public void GenericInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GenericInput
            //Assert.IsInstanceOf(typeof(GenericInput), instance);
        }

        /// <summary>
        /// Test deserialize a DAGStringInput from type GenericInput
        /// </summary>
        [Test]
        public void DAGStringInputDeserializeFromGenericInputTest()
        {
            // TODO uncomment below to test deserialize a DAGStringInput from type GenericInput
            //Assert.IsInstanceOf(typeof(GenericInput), JsonConvert.DeserializeObject<GenericInput>(new DAGStringInput().ToJson()));
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Test]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Default'
        /// </summary>
        [Test]
        public void DefaultTest()
        {
            // TODO unit test for the property 'Default'
        }
        /// <summary>
        /// Test the property 'Spec'
        /// </summary>
        [Test]
        public void SpecTest()
        {
            // TODO unit test for the property 'Spec'
        }

    }

}
