/* 
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Model;
using QueenbeeSDK;

using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing IOBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IOBaseTests
    {
        // TODO uncomment below to declare an instance variable for IOBase
        //private IOBase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IOBase
            //instance = new IOBase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IOBase
        /// </summary>
        [Test]
        public void IOBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" IOBase
            //Assert.IsInstanceOf(typeof(IOBase), instance);
        }

        /// <summary>
        /// Test deserialize a DAG from type IOBase
        /// </summary>
        [Test]
        public void DAGDeserializeFromIOBaseTest()
        {
            // TODO uncomment below to test deserialize a DAG from type IOBase
            //Assert.IsInstanceOf(typeof(IOBase), JsonConvert.DeserializeObject<IOBase>(new DAG().ToJson()));
        }

        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Test]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Test]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Test]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
