/* 
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Model;
using QueenbeeSDK;

using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing OpenAPIGenBaseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpenAPIGenBaseModelTests
    {
        // TODO uncomment below to declare an instance variable for OpenAPIGenBaseModel
        //private OpenAPIGenBaseModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OpenAPIGenBaseModel
            //instance = new OpenAPIGenBaseModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void OpenAPIGenBaseModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), instance);
        }

        /// <summary>
        /// Test deserialize a DAGFileInput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGFileInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGFileInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGFileInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a Recipe from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void RecipeDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a Recipe from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new Recipe().ToJson()));
        }
        /// <summary>
        /// Test deserialize a License from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void LicenseDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a License from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new License().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGFolderInput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGFolderInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGFolderInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGFolderInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGPathInput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGPathInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGPathInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGPathInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a IOBase from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void IOBaseDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a IOBase from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new IOBase().ToJson()));
        }
        /// <summary>
        /// Test deserialize a TaskArgument from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void TaskArgumentDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a TaskArgument from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new TaskArgument().ToJson()));
        }
        /// <summary>
        /// Test deserialize a Dependency from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DependencyDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a Dependency from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new Dependency().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGTask from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGTaskDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGTask from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGTask().ToJson()));
        }
        /// <summary>
        /// Test deserialize a ArtifactSource from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void ArtifactSourceDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a ArtifactSource from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new ArtifactSource().ToJson()));
        }
        /// <summary>
        /// Test deserialize a BaseReference from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void BaseReferenceDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a BaseReference from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new BaseReference().ToJson()));
        }
        /// <summary>
        /// Test deserialize a Maintainer from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void MaintainerDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a Maintainer from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new Maintainer().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGArrayInput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGArrayInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGArrayInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGArrayInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a GenericOutput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void GenericOutputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a GenericOutput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new GenericOutput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGObjectInput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGObjectInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGObjectInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGObjectInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGBooleanInput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGBooleanInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGBooleanInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGBooleanInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a MetaData from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void MetaDataDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a MetaData from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new MetaData().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGTaskLoop from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGTaskLoopDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGTaskLoop from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGTaskLoop().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGNumberInput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGNumberInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGNumberInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGNumberInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a GenericInput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void GenericInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a GenericInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new GenericInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DAGIntegerInput from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void DAGIntegerInputDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a DAGIntegerInput from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new DAGIntegerInput().ToJson()));
        }
        /// <summary>
        /// Test deserialize a TaskPathArgument from type OpenAPIGenBaseModel
        /// </summary>
        [Test]
        public void TaskPathArgumentDeserializeFromOpenAPIGenBaseModelTest()
        {
            // TODO uncomment below to test deserialize a TaskPathArgument from type OpenAPIGenBaseModel
            //Assert.IsInstanceOf(typeof(OpenAPIGenBaseModel), JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(new TaskPathArgument().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
