/* 
 * Queenbee Recipe Schema
 *
 * Documentation for Queenbee recipe schema.
 *
 * The version of the OpenAPI document: 1.6.6
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using QueenbeeSDK.Model;
using QueenbeeSDK;

using System.Reflection;
using Newtonsoft.Json;

namespace QueenbeeSDK.Test
{
    /// <summary>
    ///  Class for testing PathOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PathOutputTests
    {
        // TODO uncomment below to declare an instance variable for PathOutput
        //private PathOutput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PathOutput
            //instance = new PathOutput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PathOutput
        /// </summary>
        [Test]
        public void PathOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PathOutput
            //Assert.IsInstanceOf(typeof(PathOutput), instance);
        }

        /// <summary>
        /// Test deserialize a TaskPathReturn from type PathOutput
        /// </summary>
        [Test]
        public void TaskPathReturnDeserializeFromPathOutputTest()
        {
            // TODO uncomment below to test deserialize a TaskPathReturn from type PathOutput
            //Assert.IsInstanceOf(typeof(PathOutput), JsonConvert.DeserializeObject<PathOutput>(new TaskPathReturn().ToJson()));
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
