//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Recipe
{
	public partial interface IDag {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class DAG: QueenbeeSDK.Interface.Recipe.IDag {}
}
