//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Recipe
{
	public partial interface IRecipe {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class Recipe: QueenbeeSDK.Interface.Recipe.IRecipe {}
}
