//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Recipe
{
	public partial interface ITask {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class DAGTask: QueenbeeSDK.Interface.Recipe.ITask {}
	public partial class DAGTaskLoop: QueenbeeSDK.Interface.Recipe.ITask {}
}
