//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io
{
	public partial interface ICommon {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class FromOutput: QueenbeeSDK.Interface.Io.ICommon {}
	public partial class GenericInput: QueenbeeSDK.Interface.Io.ICommon {}
	public partial class GenericOutput: QueenbeeSDK.Interface.Io.ICommon {}
	public partial class IOAliasHandler: QueenbeeSDK.Interface.Io.ICommon {}
	public partial class IOBase: QueenbeeSDK.Interface.Io.ICommon {}
	public partial class PathOutput: QueenbeeSDK.Interface.Io.ICommon {}
}
