//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io
{
	public partial interface IFunction {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class FunctionArrayInput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionArrayOutput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionBooleanInput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionBooleanOutput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionFileInput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionFileOutput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionFolderInput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionFolderOutput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionIntegerInput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionIntegerOutput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionJSONObjectInput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionJSONObjectOutput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionNumberInput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionNumberOutput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionPathInput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionPathOutput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionStringInput: QueenbeeSDK.Interface.Io.IFunction {}
	public partial class FunctionStringOutput: QueenbeeSDK.Interface.Io.IFunction {}
}
