//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace QueenbeeSDK.Interface.Io
{
	public partial interface IReference {}
}

//Classes implemented this interface:
namespace QueenbeeSDK
{
	public partial class FileReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class FolderReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class InputFileReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class InputFolderReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class InputPathReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class InputReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class ItemReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class TaskFileReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class TaskFolderReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class TaskPathReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class TaskReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class ValueFileReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class ValueFolderReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class ValueListReference: QueenbeeSDK.Interface.Io.IReference {}
	public partial class ValueReference: QueenbeeSDK.Interface.Io.IReference {}
}
