name: CD

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2

      - name: Update Assembly Version
        run: |
          python .github/workflows/update_assembly_version.py
          
      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release /nowarn:CS0472,CS0108

      - name: Run Unit Tests
        run: |
          dotnet test ./src/QueenbeeSDK.Tests/ --configuration Release
          
      - name: Deploy
        working-directory: src/QueenbeeSDK
        run: |
          dotnet pack --configuration Release
          dotnet nuget push bin\Release\QueenbeeSDK.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json


